with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  # payment service
  github.com/milkrage/microservices-course-homework/payment/internal/service:
    config:
      include-regex: ".*Service"

  # inventory service
  github.com/milkrage/microservices-course-homework/inventory/internal/service:
    config:
      include-regex: ".*Service"

  github.com/milkrage/microservices-course-homework/inventory/internal/repository:
    config:
      include-regex: ".*Repository"

  # order service
  github.com/milkrage/microservices-course-homework/order/internal/service:
    config:
      include-regex: ".*Service"

  github.com/milkrage/microservices-course-homework/order/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/milkrage/microservices-course-homework/order/internal/client/grpc:
    config:
      include-regex: ".*Client"
